@@include('jquery.js', {})
@@include('slick.js', {})
@@include('jquery.mCustomScrollbar.concat.min.js', {})
@@include('jquery.dpNumberPicker-1.0.1.js', {})
@@include('jquery.nice-select.min.js', {})
@@include('jquery.rateyo.min.js', {})
@@include('jquery.fancybox.min.js', {})
@@include('jquery.validate.js', {})
@@include('jquery.mask.js', {})

